# This is kamal's deploy.yml configuration file for a IP address destination.
#
servers:
  web:
    - 34.129.63.249
proxy:
  ssl: false
  host: 34.129.63.249

builder:
  arch: amd64

ssh:
  user: root
